name: Check Formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    check-formatting:
        name: Check Formatting
        runs-on: ubuntu-latest
        strategy:
            matrix:
                path:
                    - "Serializer"
                    - "LibTerraria"
                    - "Server"
        steps:
        - uses: actions/checkout@v2
        - name: Run clang-format style check for C/C++ programs.
          uses: jidicula/clang-format-action@7709c2a70b025f444ab479907c0d72f3beea5a63
          with:
            clang-format-version: '12'
            check-path: ${{ matrix.path }}
